### ISSUE TITLE
Feed bugs

### ISSUE THREAD

**Issue by popescurry** [anschelsc/simplecta#3]
Hello,

I am working with other group members in Professor Schaffer’s capstone class for the simplecta app. Currently, if I subscribe an RSS feed in the Atom feed subscription field, it subscribes to the feed but doesn’t show the title of the subscribed feed. All i see is (unsubscribe) which doesn’t help with identifying the specific feed especially since we plan on using the feed titles in our app design. However, It shows the title if i subscribe to the RSS feed field. 

Kindly check if it can possibly be fixed.

**Comment by anschelsc** [comment]
Closing since there was no response ever.

**Comment by anschelsc** [comment]
Fixed (if I actually understood what the issue was), in the sense that there is now an error message, by commit 34269d4cb8e0919334d87b044842156fde18b91c.
