### ISSUE TITLE
Can't see URLs for RSS

### ISSUE THREAD

**Issue by cullenschaffer** [anschelsc/simplecta#5]
The main site I use for political cartoons doesn't tell you what the RSS feeds are anymore and it's been so long that I've forgotten.  I'd like to be able to view the URLs associated with each of the feeds I'm subscribed to, but currently Simplecta doesn't allow me to see them.  If I could, I could copy-and-paste the one for an old cartoon and modify it to subscribe to the new one.

**Comment by anschelsc** [comment]
Partial fix while I remember how to JQuery: feed URLs show up when you hover over the feed name on the "manage subscriptions" page. Commit 04487f58868baee8a31ab802c446e84d9276abe4.

**Comment by anschelsc** [comment]
...and done. I'll make a separate issue for the fact that it's unstyled.
